import { VertexAI } from '@google-cloud/vertexai';
import dotenv from 'dotenv';

dotenv.config();

// Initialize Vertex AI with Application Default Credentials (ADC)
// Automatically picks up credentials when running on GCP Cloud Run
const project = process.env.GOOGLE_CLOUD_PROJECT || 'your-gcp-project-id';
const location = process.env.GOOGLE_CLOUD_LOCATION || 'us-central1';

const vertex_ai = new VertexAI({ project, location });

export interface AnalyzedClause {
  id: string;
  clauseTitle: string;
  originalText: string;
  documentReference: string;
  riskPercentage: number;
  riskCategory: 'HIGH' | 'MODERATE' | 'OK';
  suggestion: string;
}

export interface ContractAnalysisResponse {
  summary: {
    totalClauses: number;
    highRiskCount: number;
    moderateRiskCount: number;
    okCount: number;
  };
  clauses: AnalyzedClause[];
}

export async function analyzeDocument(buffer: Buffer, mimeType: string): Promise<ContractAnalysisResponse> {
  // Use gemini-2.0-flash as the primary manager and gemini-1.5-pro-002 as instructed for deep extraction.
  // We use the JSON schema output mode to enforce the strict TypeScript interface.
  const generativeModel = vertex_ai.getGenerativeModel({
    model: 'gemini-2.5-flash', // Upgraded to Gemini 2.5 flash as requested
    generationConfig: {
      temperature: 0.1, // Highly deterministic
      responseMimeType: 'application/json',
    },
  });

  const prompt = `
You are the Manager Agent of LEXGUARD, a highly scalable AI Rights & Contract Intelligence platform.
Your task is to orchestrate the analysis of the provided legal document to protect users from exploitative legal agreements.

Internally execute this multi-agent workflow:
1. Clause Extractor Agent (gemini-1.5-pro): Extract every explicit and implicit clause. Identify the approximate structural text anchor (e.g., "Paragraph 4").
2. Risk Evaluator Agent (gemini-2.0-flash): Evaluate each text item against asymmetric legal liabilities or vague definitions. Append an exact numeric risk percentage (0 to 100).
   - Categorize as HIGH (>=70), MODERATE (31-69), or OK (<=30).
3. Remediation Advisor Agent (gemini-1.5-pro): For any clause > 0% risk, build actionable counter-offer suggestions detailing safer alternative phrasing. For safe clauses, output "OK".
4. Manager Agent (You): Aggregate all data, strictly sort the array in DESCENDING order of riskPercentage, calculate the summary KPI totals, and output the exact JSON structure.

Strict JSON Response Schema:
{
  "summary": {
    "totalClauses": number,
    "highRiskCount": number,
    "moderateRiskCount": number,
    "okCount": number
  },
  "clauses": [
    {
      "id": "string",
      "clauseTitle": "string",
      "originalText": "string",
      "documentReference": "string",
      "riskPercentage": number,
      "riskCategory": "HIGH" | "MODERATE" | "OK",
      "suggestion": "string"
    }
  ]
}
`;

  const documentPart = {
    inlineData: {
      data: buffer.toString('base64'),
      mimeType: mimeType,
    },
  };

  const request = {
    contents: [{ role: 'user', parts: [{ text: prompt }, documentPart] }],
  };

  const response = await generativeModel.generateContent(request);
  const responseText = response.response.candidates?.[0].content.parts[0].text;

  if (!responseText) {
    throw new Error('No content generated by Vertex AI.');
  }

  // Parse and enforce the sorting manually just in case the LLM didn't sort perfectly
  const parsedResponse: ContractAnalysisResponse = JSON.parse(responseText);
  parsedResponse.clauses.sort((a, b) => b.riskPercentage - a.riskPercentage);

  return parsedResponse;
}
